package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type templateReset struct {
	Package string
	Structs []templateResetStruct
}

type templateResetStruct struct {
	Name   string
	Fields []templateResetField
}

type templateResetField struct {
	Name        string
	Type        string
	IsSlice     bool
	IsMap       bool
	IsPointer   bool
	IsStruct    bool
	IsPrimitive bool
	ZeroValue   string
	InnerType   string
}

const templateStr = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package {{.Package}}

{{range .Structs}}
func (s *{{.Name}}) Reset() {
{{range .Fields}}
{{- if .IsSlice}}
	s.{{.Name}} = s.{{.Name}}[:0]
{{- else if .IsMap}}
	clear(s.{{.Name}})
{{- else if .IsPointer}}
	if s.{{.Name}} != nil {
{{- if .IsStruct}}
		if resetter, ok := s.{{.Name}}.(interface{ Reset() }); ok {
			resetter.Reset()
		}
{{- else}}
		*s.{{.Name}} = {{.ZeroValue}}
{{- end}}
	}
{{- else if .IsStruct}}
	if resetter, ok := s.{{.Name}}.(interface{ Reset() }); ok {
		resetter.Reset()
	}
{{- else if .IsPrimitive}}
	s.{{.Name}} = {{.ZeroValue}}
{{- end}}
{{end}}
}
{{end}}
`

var tmpl = template.Must(template.New("reset").Parse(templateStr))

func main() {
	fname := os.Getenv("GOFILE")
	if fname == "" {
		fmt.Fprintln(os.Stderr, "GOFILE not set")
		os.Exit(1)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, fname, nil, parser.ParseComments)
	if err != nil {
		err = fmt.Errorf("parse file error: %w", err)
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var structs []templateResetStruct

	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if !hasGenerateResetComment(gd.Doc, ts.Doc) {
				continue
			}

			var fields []templateResetField
			for _, field := range st.Fields.List {
				for _, name := range field.Names {
					fields = append(fields, analyzeField(name.Name, field.Type))
				}
			}

			structs = append(structs, templateResetStruct{
				Name:   ts.Name.Name,
				Fields: fields,
			})
		}
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, templateReset{
		Package: f.Name.Name,
		Structs: structs,
	})
	if err != nil {
		err = fmt.Errorf("applies a parsed template error: %w", err)
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	bufFmt, err := format.Source(buf.Bytes())
	if err != nil {
		err = fmt.Errorf("format error: %w", err)
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	outPath := filepath.Join(filepath.Dir(fname), "reset.gen.go")
	err = os.WriteFile(outPath, bufFmt, 0644)
	if err != nil {
		err = fmt.Errorf("write file error: %w", err)
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func hasGenerateResetComment(groups ...*ast.CommentGroup) bool {
	for _, cg := range groups {
		if cg == nil {
			continue
		}
		for _, c := range cg.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
	}
	return false
}

func analyzeField(name string, t ast.Expr) templateResetField {
	field := templateResetField{Name: name}

	switch expr := t.(type) {
	case *ast.ArrayType:
		field.IsSlice = true
		field.Type = "[]" + getTypeName(expr.Elt)
	case *ast.MapType:
		field.IsMap = true
		field.Type = "map[" + getTypeName(expr.Key) + "]" + getTypeName(expr.Value)
	case *ast.StarExpr:
		field.IsPointer = true
		field.InnerType = getTypeName(expr.X)
		if _, ok := expr.X.(*ast.StructType); ok {
			field.IsStruct = true
		} else {
			field.IsPrimitive = true
			field.ZeroValue = getZeroValue(field.InnerType)
		}
	case *ast.StructType:
		field.IsStruct = true
		field.Type = "struct{}"
	default:
		field.IsPrimitive = true
		field.Type = expr.(*ast.Ident).Name
		field.ZeroValue = getZeroValue(field.Type)
	}

	return field
}

func getTypeName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.ArrayType:
		return "[]" + getTypeName(e.Elt)
	case *ast.MapType:
		return "map[" + getTypeName(e.Key) + "]" + getTypeName(e.Value)
	case *ast.StarExpr:
		return "*" + getTypeName(e.X)
	default:
		return ""
	}
}

func getZeroValue(typeName string) string {
	switch typeName {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "byte", "rune":
		return "0"
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return fmt.Sprintf("%s{}", typeName)
	}
}
